package com.carddemo.account.dto;

import java.math.BigDecimal;

public record AccountViewResponse(
        long accountId,
        String errorMessage,
        String activeStatus,
        BigDecimal currentBalance,
        BigDecimal creditLimit,
        BigDecimal cashCreditLimit,
        BigDecimal currentCycleCredit,
        BigDecimal currentCycleDebit,
        String openDate,
        String expirationDate,
        String reissueDate,
        String groupId,
        Long customerId,
        String customerSsnFormatted,
        Integer ficoScore,
        String dob,
        String firstName,
        String middleName,
        String lastName,
        String addrLine1,
        String addrLine2,
        String cityLine,
        String stateCd,
        String zip,
        String countryCd,
        String phone1,
        String phone2,
        String govtId,
        String eftAccountId,
        String priCardHolderInd) {

    public static AccountViewResponse error(long accountId, String message) {
        return new AccountViewResponse(
                accountId,
                message,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }
}
