CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT PRIMARY KEY,
    active_status VARCHAR(1) NOT NULL,
    current_balance DECIMAL(12,2) NOT NULL,
    credit_limit DECIMAL(12,2) NOT NULL,
    cash_credit_limit DECIMAL(12,2) NOT NULL,
    open_date DATE,
    expiration_date DATE,
    reissue_date DATE,
    current_cycle_credit DECIMAL(12,2) NOT NULL,
    current_cycle_debit DECIMAL(12,2) NOT NULL,
    address_zip VARCHAR(10),
    group_id VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT PRIMARY KEY,
    first_name VARCHAR(25),
    middle_name VARCHAR(25),
    last_name VARCHAR(25),
    address_line_1 VARCHAR(50),
    address_line_2 VARCHAR(50),
    address_line_3 VARCHAR(50),
    state_code VARCHAR(2),
    country_code VARCHAR(3),
    zip VARCHAR(10),
    phone_1 VARCHAR(15),
    phone_2 VARCHAR(15),
    ssn VARCHAR(9),
    govt_issued_id VARCHAR(20),
    date_of_birth DATE,
    eft_account_id VARCHAR(10),
    primary_card_holder_ind VARCHAR(1),
    fico_score INTEGER
);

CREATE TABLE IF NOT EXISTS cards (
    card_number VARCHAR(16) PRIMARY KEY,
    account_id BIGINT NOT NULL,
    cvv INTEGER,
    embossed_name VARCHAR(50),
    expiration_date DATE,
    active_status VARCHAR(1),
    CONSTRAINT fk_cards_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

CREATE TABLE IF NOT EXISTS card_xrefs (
    card_number VARCHAR(16) PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    CONSTRAINT fk_card_xrefs_card
        FOREIGN KEY (card_number) REFERENCES cards(card_number)
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id VARCHAR(16) PRIMARY KEY,
    transaction_type_code VARCHAR(2) NOT NULL,
    transaction_category_code INTEGER NOT NULL,
    source VARCHAR(10),
    description VARCHAR(100),
    amount DECIMAL(11,2) NOT NULL,
    merchant_id BIGINT,
    merchant_name VARCHAR(50),
    merchant_city VARCHAR(50),
    merchant_zip VARCHAR(10),
    card_number VARCHAR(16) NOT NULL,
    original_timestamp TIMESTAMP,
    processed_timestamp TIMESTAMP,
    CONSTRAINT fk_transactions_card
        FOREIGN KEY (card_number) REFERENCES cards(card_number)
);

CREATE TABLE IF NOT EXISTS transaction_category_balances (
    account_id BIGINT NOT NULL,
    transaction_type_code VARCHAR(2) NOT NULL,
    transaction_category_code INTEGER NOT NULL,
    balance DECIMAL(11,2) NOT NULL,
    PRIMARY KEY (account_id, transaction_type_code, transaction_category_code),
    CONSTRAINT fk_tcatbal_account
        FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

CREATE TABLE IF NOT EXISTS disclosure_groups (
    account_group_id VARCHAR(10) NOT NULL,
    transaction_type_code VARCHAR(2) NOT NULL,
    transaction_category_code INTEGER NOT NULL,
    interest_rate DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (account_group_id, transaction_type_code, transaction_category_code)
);

CREATE TABLE IF NOT EXISTS daily_transactions (
    transaction_id VARCHAR(16) PRIMARY KEY,
    transaction_type_code VARCHAR(2) NOT NULL,
    transaction_category_code INTEGER NOT NULL,
    source VARCHAR(10),
    description VARCHAR(100),
    amount DECIMAL(11,2) NOT NULL,
    merchant_id BIGINT,
    merchant_name VARCHAR(50),
    merchant_city VARCHAR(50),
    merchant_zip VARCHAR(10),
    card_number VARCHAR(16) NOT NULL,
    original_timestamp TIMESTAMP,
    processed_timestamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_transaction_rejections (
    rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(16) NOT NULL,
    reason_code INTEGER NOT NULL,
    reason_description VARCHAR(200) NOT NULL
);
